export enum ENV_KEY {
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_SCHEMA = 'DB_SCHEMA',
  DB_SYNCHRONIZE = 'DB_SYNCHRONIZE',
  DB_LOGGING = 'DB_LOGGING',

  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRATION = 'JWT_EXPIRATION',
}

export const INJECTION_TOKEN = {
  AUDIT_SERVICE: Symbol.for('AUDIT_SERVICE'),
};

export enum HEADER_KEY {
  LOG_ID = 'X-Log-ID',
}

export const ERR_CODE = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'.toLowerCase(),
};

export enum APP_ACTION {
  HANDLE_EXCEPTION = 'HANDLE_EXCEPTION',
}

export enum ENTITY_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}
